### ISSUE TITLE
Feature Request: Support for all HP OMEN desktop lights

### ISSUE THREAD

**Issue by jame25** [chiahsing/omen-light#1]
I greatly appreciate this project - now having recently moved to Linux full time. My HP OMEN 30L has two lights on the front, an upper and a lower (fan ring light). I am able to disable the upper (front) light successfully, along with the internal (Chase) lights.

What remains are are the lower front light and a light around the CPU.

If I can assist by providing more specific information, please let me know.

**Comment by chiahsing** [comment]
Patches are welcome.
